---
- name: Create destination directory for genesis file
  become: true
  become_method: sudo
  file:
    path: /etc/besu/genesis
    state: directory
    mode: '0755'

- name: copy genesis file
  become: true
  become_method: sudo
  copy: 
    src: "{{besu_genesis_origin}}"
    dest: "{{besu_genesis_path}}"

# - name: Create destination directory for config file
#   become: true
#   become_method: sudo
#   file:
#     path: /etc/besu/config
#     state: directory
#     mode: '0755'

# - name: copy config file
#   become: true
#   become_method: sudo
#   copy: 
#     src: ~/Besu-Benhmark-EHR/besu/config.toml 
#     dest: /etc/besu/config/config.toml

- name: Create destination directory for keys
  become: true
  become_method: sudo
  file:
    path: /etc/besu/keys
    state: directory
    mode: '0755'
- name: copy key file
  become: true
  become_method: sudo
  copy: 
    src:  ~/Besu-Benhmark-EHR/besu/keys/keys/{{ ansible_hostname }}/key
    dest: /etc/besu/keys/key
- name: copy public key file
  become: true
  become_method: sudo
  copy: 
    src:  ~/Besu-Benhmark-EHR/besu/keys/keys/{{ ansible_hostname }}/key.pub
    dest: /etc/besu/keys/key.pub
        
- name: Create destination directory for static-nodes.json file
  become: true
  become_method: sudo
  file:
    path: /etc/besu
    state: directory
    mode: '0755'
- name: copy static-nodes.json file
  become: true
  become_method: sudo
  copy: 
    src:  ~/Besu-Benhmark-EHR/besu/static-nodes.json
    dest: /etc/besu/static-nodes.json
