
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: 'yes'
- name: Install OpenJDK 17
  become: true
  become_method: sudo
  apt:
    name: openjdk-17-jdk
    state: present
