---
- name: Ensure Besu group exists
  group:
    name: "{{ besu_group }}"
    state: present
  become: true

- name: Create Besu user
  user:
    comment:  Besu client user
    name: "{{ besu_user }}"
    group: "{{ besu_group }}"
  become: true

- name: Create base directory
  file:
    path: "{{ besu_base_dir }}"
    state: directory
    owner: "{{ besu_user }}"
    group: "{{ besu_group }}"
  become: true

- name: Create install directory
  file:
    path: "{{ besu_install_dir }}"
    state: directory
    owner: "{{ besu_user }}"
    group: "{{ besu_group }}"
  become: true

- name: Create log directory
  file:
    path: "{{ besu_log_dir }}"
    state: directory
    owner: "{{ besu_user }}"
    group: "{{ besu_group }}"
  become: true

- name: Setup logrotate
  template:
    src: "logrotate/besu"
    dest: "/etc/logrotate.d/besu"
  become: true

- name: Extract Besu source to install directory
  unarchive:
    src: "{{ '/tmp/besu/build/distributions/besu-' + besu_version + '.tar.gz' if besu_build_from_source else besu_download_url }}"
    remote_src: "{{ false if besu_build_from_source else true }}"
    dest: "{{ besu_install_dir }}"
    owner: "{{ besu_user }}"
    group: "{{ besu_group }}"
    mode: '0775'
    extra_opts:
      - --strip-components
      - '1'
  become: true

- name: Create a symlink to current
  file:
    src: "{{ besu_install_dir }}/"
    dest: "{{ besu_current_dir }}"
    state: link
  become: true
  register: link_current

- name: Agregar Besu al PATH en /etc/profile
  become: true
  lineinfile:
    path: /etc/profile
    line: 'export PATH="$PATH:/opt/besu"'

- name: Agregar binarios Besu al PATH en /etc/profile
  become: true
  lineinfile:
    path: /etc/profile
    line: 'export PATH="$PATH:/opt/besu/besu-23.10.3/bin"'

- name: Reload Profile
  become: true
  shell: source /etc/profile
  args:
    executable: /bin/bash
  async: 0
  poll: 0



- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    besu_state_updates: "{{ besu_state_updates + ['besu.install_dir'] }}"
  when: link_current is changed





