---
- hosts: BesuBotNodes
  force_handlers: True
 
  roles:
    - role: hyperledger_besu_custom
      vars:
        besu_node_private_key_file: /etc/besu/keys/key
        besu_version: 23.10.3
        besu_network: custom 
        besu_miner_enabled: "true"
        besu_genesis_path: /etc/besu/genesis/genesis.json
        besu_config_dir: /etc/besu
        besu_rpc_http_enabled: true
        besu_rpc_http_host : 0.0.0.0
        besu_rpc_http_port : 8545

- hosts: BesuHosts
  force_handlers: True
 
  roles:
    - role: hyperledger_besu_custom
      vars:
        besu_version: 23.10.3
        besu_node_private_key_file: /etc/besu/keys/key
        besu_network: custom 
        besu_miner_enabled: "true"
        besu_genesis_path: /etc/besu/genesis/genesis.json
        besu_config_dir: /etc/besu/config
        besu_rpc_http_enabled: true
        besu_rpc_http_host : 0.0.0.0
        besu_rpc_http_port : 8545