- hosts: BesuHosts
  force_handlers: True
 
  roles:
    - role: hyperledger_besu_custom
      vars:
        besu_version: 23.10.2
        besu_node_private_key_file: /etc/besu/keys/key
        besu_bootnodes: ["enode://4e11b2200e98289050e4555d7496876423524b93df4993cc447b40b5e4e1a9691417fe930e2ac3c95905cb0cfe422f916487190a04616ebaf55fecff7ebb366c@10.0.64.2:30303"]
        #besu_static_nodes_file: /etc/besu/static-nodes.json
        besu_discovery_enabled: true
        besu_network: custom 
        besu_miner_enabled: "false"
        besu_genesis_origin: ~/Besu-Benhmark-EHR/besu/keys/genesis.json
        besu_genesis_path: /etc/besu/genesis/genesis.json
        besu_config_dir: /etc/besu
        besu_rpc_http_enabled: true
        besu_rpc_http_host : 0.0.0.0  
        besu_rpc_http_port : 8545
        besu_rpc_http_api: ["ADMIN","QBFT", "DEBUG", "NET", "ETH", "MINER", "WEB3"]
        besu_rpc_ws_enabled: true
        besu_rpc_ws_host: 0.0.0.0
        besu_rpc_ws_port: 8546
        besu_rpc_ws_api: ["ADMIN","QBFT", "DEBUG", "NET", "ETH", "MINER", "WEB3"]
        besu_enable_tx_pool_options: true
        besu_tx_pool: layered
        besu_tx_pool_max_future_by_sender: 25000
        besu_tx_pool_layer_max_capacity: 50000000
        besu_tx_pool_max_prioritized: 5000
        besu_config_template: "simple-config.toml.j2"
        # besu_host_allowlist: ["*"]
        # besu_rpc_http_cors_origins: ["*"]
        # besu_graphql_http_cors_origins: ["*"]