---
- hosts: BesuHosts
  force_handlers: True
 
  pre_tasks:
    - name: Install OpenJDK 11
      become: true
      become_method: sudo
      apt:
        name: openjdk-11-jdk
        state: present  # Puedes cambiar a 'latest' si quieres siempre la última versión
    - name: Create destination directory for genesis file
      become: true
      become_method: sudo
      file:
        path: /etc/besu/genesis
        state: directory
        mode: '0755'    
    - name: copy genesis file
      become: true
      become_method: sudo
      copy: 
        src:  ~/Besu-Benhmark-EHR/besu/genesis.json 
        dest: /etc/besu/genesis/genesis.json   
    - name: Create destination directory for config file
      become: true
      become_method: sudo
      file:
        path: /etc/besu/config
        state: directory
        mode: '0755'
    - name: copy config file
      become: true
      become_method: sudo
      copy: 
        src:  ~/Besu-Benhmark-EHR/besu/config.toml 
        dest: /etc/besu/config/config.toml
              
  roles:
    - role: consensys.hyperledger_besu
      vars:
        besu_version: 23.10.3
        besu_network: custom 
        besu_miner_enabled: "true"
        besu_genesis_path: /etc/besu/genesis/genesis.json
        besu_config_dir: /etc/besu
        besu_rpc_http_enabled: true
        besu_rpc_http_host : 0.0.0.0
        besu_rpc_http_port : 8545

- hosts: BesuHosts
  force_handlers: True
 

  pre_tasks:
    - name: Install OpenJDK 11
      become: true
      become_method: sudo
      apt:
        name: openjdk-11-jdk
        state: present  # Puedes cambiar a 'latest' si quieres siempre la última versión
    - name: Create destination directory for genesis file
      become: true
      become_method: sudo
      file:
        path: /etc/besu/genesis
        state: directory
        mode: '0755'    
    - name: copy genesis file
      become: true
      become_method: sudo
      copy: 
        src:  ~/Besu-Benhmark-EHR/besu/genesis.json 
        dest: /etc/besu/genesis/genesis.json
              
  roles:
    - role: consensys.hyperledger_besu
      vars:
        besu_version: 23.10.3
        besu_network: custom 
        besu_miner_enabled: "true"
        besu_genesis_path: /etc/besu/genesis/genesis.json
        besu_config_dir: /etc/besu/config
        besu_rpc_http_enabled: true
        besu_rpc_http_host : 0.0.0.0
        besu_rpc_http_port : 8545