---
- hosts: BesuHosts
  force_handlers: True
 

  pre_tasks:
    - name: Install OpenJDK 11
      become: true
      become_method: sudo
      apt:
        name: openjdk-11-jdk
        state: present  # Puedes cambiar a 'latest' si quieres siempre la última versión
    - name: copy genesis file
        copy: src=~/Besu-Benhmark-EHR/besu/genesis.json dest=/etc/besu/genesis/genesis.json
       

  roles:
    - role: consensys.hyperledger_besu
      vars:
        besu_version: 23.10.3
        besu_network: custom 
        besu_miner_enabled: "true"
        besu_genesis_path: /etc/besu/genesis/genesis.json
        besu_rpc_http_enabled: true
        besu_rpc_http_host : 0.0.0.0
        besu_rpc_http_port : 8545